#!/usr/bin/env php
<?php declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';
require_once __DIR__ . '/bootstrap.php';

use Webman\Console\Command;

echo "ℹ️ Run in debug mode!\n";

$cli = new Command();
$cli->setName('webman-rabbitmq-test cli');
foreach (config('plugin', []) as $projects) {
    foreach ($projects as $project) {
        foreach ($project['command'] ?? [] as $command) {
            $cli->add(new $command);
        }
    }
}

try {
    $cli->run();
} catch (Exception $e) {
    exit($e->getMessage());
}